services:
  rust:
    build:
      context: ./Docker/rust
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - ./:/workspace
    working_dir: /workspace
  mariadb:
    build:
      context: ./Docker/mariadb
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./Docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
